var code = ''; // Global variable to store the generated code
var getCode = " ";
var buttonValue; // for button boolean value 
var str = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@#$"; // all possible characters for the code

function generateCode() {
    // Create variables to store generated codes and the type of characters we want to show as codes
    code = ' ';
    // Generate character multiple times using for loop
    for (var i = 1; i <= 8; i++) {
        var char = Math.floor(Math.random() * str.length);
        code += str.charAt(char); // accumulate the generated characters into a string of 8
    }
    return code;
}

// Get HTML element to display
document.getElementById("codes").innerHTML = generateCode();

// Disable button 
function disableButton(buttonValue) {
    document.getElementById("submit").disabled = buttonValue;
    if (buttonValue == true) {
        // set button and label color translucent
        document.getElementById("submit").style.backgroundColor = "rgba(73, 119, 209, 0.3)";
        document.getElementById("submit").style.color = "rgba(255, 255, 255, 0.5)";
    } else {
        // set button and label color with no transparency
        document.getElementById("submit").style.backgroundColor = "rgba(73, 119, 209, 1)";
        document.getElementById("submit").style.color = "rgba(255, 255, 255, 1)";
    }
}

function evaluateCode() {
    getCode = document.getElementById("code_entered").value; // get the characters entered by user
    var charSet1 = getCode.trim(); // remove any hidden characters 
    var charSet2 = code.trim(); // remove any hidden characters generated by the system

    if (charSet1.length == charSet2.length && charSet1 === charSet2) {
        // If the codes match
        alert("Code verified successfully!");
        disableButton(false);
    } else {
        // If the codes do not match
        alert("Invalid code. Please try again.");
        disableButton(true);
    }
}